### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Huluti** [AntumDeluge/debreate#3]
Hi !
I think the project website could be even better. It could be more modern, more comprehensive and more attractive. I have started to work on a prototype to show you what you can expect. We can discuss here about the way to lead this proposition. (create a new repo?, use Github Pages to host it?).
Here a [screenshot](http://pix.toile-libre.org/upload/original/1475247394.png) of my prototype.

Current features:
- FAQ
- Downloads section
- Contributors list (with Github API)
Website is designed with HTML5/CSS3 & jQuery.

Of course, it's only a proposition, nothing is urgent, we must take the time to discuss it. If you are interested by, please make me feedback on what's missing and what's can be improving.

**Comment by AntumDeluge** [comment]
Wow! That looks absolutely amazing! You are an excellent web developer, & I love this idea. I have a hard time maintaining the website because I am not experienced in any web languages like HTML, CSS, Javascript, or PHP. I also work on many different projects, including ones not involving software.

Something else that you could add to the website, I created an IRC channel on Freenode that I sometimes use, [#debreate](https://webchat.freenode.net/?channels=#debreate). I think it would be good to have that listed. Though, I am not always active in web chat.

I was hoping to learn the API & save the web chat logs to Debreate's website, that way, if I weren't on the channel when someone asked a question, I could go through the log history.

What would be the best way to maintain the website? Create another repository called "debreate-web"?

**Comment by Huluti** [comment]
Thank's!
Yes, I think it's the best way to create a "debreate-web" repo. I have seen you've created it, so I'll start to make commits on it. I'll also add the IRC section on the website.

**Comment by Huluti** [comment]
When website will be ready, how do you want to publish it? In your current Sourceforge space?

**Comment by AntumDeluge** [comment]
I was thinking GitHub Pages, but I'm new to it & don't know how it works yet.

And I'll probably just have the SF webspace redirect to GitHub.

**Comment by Huluti** [comment]
No don't create nothing. Just go in repo settings (of debreate-web), scroll down to the GitHub Pages section. Then select the master branch source and click on the Save button. Then, it will be available on http://username.github.io/repository.

**Comment by AntumDeluge** [comment]
Excellent! Thank you very much.

**Comment by Huluti** [comment]
I think website is ready to publish, I wait your feedback.
Here the latest state : http://pix.toile-libre.org/upload/original/1475685115.png

**Comment by AntumDeluge** [comment]
It looks amazing Hugo, thank you so much. It is now published.
