### ISSUE TITLE
Please make portable version.

### ISSUE THREAD

**Issue by Xeno-Idaltu** [AntumDeluge/debreate#37]
Dependencies become obsolete and/or unsupported. Developing an official appimage, flatpak, and/or Snap will come handy.

**Comment by AntumDeluge** [comment]
Dependencies are obsolete because the app doesn't get updated anymore.

Debreate is portable by nature. Download the zip or clone the repo & run `./init.py` or `python init.py`. But it probably won't run on most current Linux OSes as Python 2 is being outmoded.

I don't know for sure when I will be able to pick up updating the app again. Not sure if it is even worth the time with all the new ways of packaging & distributing. Especially OS independent packaging. Debreate is strictly for Debian/Ubuntu Linux distros. So its usefulness is quite limited if you want to develop for multiple OSes.

I don't know much about `appimage`, `flatpak`, or `Snap`. But I think those are pretty much what I meant by OS independent packaging. People would probably benefit more from using those to distribute their software instead of Debreate.

**Comment by Xeno-Idaltu** [comment]
I'm still able to use Debreate by installing "python2" from Ubuntu-22 with "python-wxversion_3.0.2.0" and "python-wxgtk3.0_3.0.2.0" from an earlier Ubuntu release.

Debreate is worth updating because it really helps new users to package source code installs without all that extra hassle. GUIs are also a work of art and it is a shame when when apps like Debreate, EasyMp3Gain cease to function.

Please update Debreate. Your app is very handy!

**Comment by AntumDeluge** [comment]
I am considering looking into portable packaging. But I don't know much about the different conduits. I have used Snap & Flatpak on Ubuntu (just for installing packages), but I don't know anything about AppImage.

**Comment by Xeno-Idaltu** [comment]
Seems to be working.

The only problem I came across was the Makefile, line 149 needs to specify python3

Old:
	@python install.py --target install --dir "$(DESTDIR)" --prefix "$(prefix)

New:
	@python3 install.py --target install --dir "$(DESTDIR)" --prefix "$(prefix)
